### ISSUE TITLE
Showing not connected when it is connected

### ISSUE THREAD

**Issue by kvedaa** [hugocorbucci/network-monitor#1]
Recently purchased from app store, but constantly shows there is no connection, and nothing is being written to the log file.

**Comment by hugocorbucci** [comment]
Hello,
I try to ping 4.2.2.2. Is there any chance that the network you're in blocks that IP address?

Also, how are you looking at the logs? Just saving the file? Can you send me the log itself?

**Comment by kvedaa** [comment]
Howdy,

Shortly after I logged the issue I cam across the bash script you reference and noticed that it was running a ping on 4.2.2.2

I experimented with this and noticed that the ping was not returning when performing manually. As I went through a series of other address I new to be up and running I noticed that everything that I attempted to ping failed to return.

I have started to experiment with an alternative, submitting in a telnet command to a known site on port 80, just need to make sure I handle the output cleanly.

As for the log, I am using the save function, but it simply puts out a zero byte file (I have attached two such examples, but being zero byte files, there is nothing to look at…).

Looking at the results of the shell file, on my system it does not appear to be looping, after the initial status it seems to hang. Assuming that the app is acting similarly, it might explain why nothing is being put into the log.

Ken

On June 7, 2015 at 12:40:33 AM, Hugo Corbucci (notifications@github.com) wrote:

Hello,
I try to ping 4.2.2.2. Is there any chance that the network you're in blocks that IP address?

Also, how are you looking at the logs? Just saving the file? Can you send me the log itself?

**Comment by hugocorbucci** [comment]
hmmm I had similar issues when I was running pings from virtual machines in network blocked clouds. If the ping program never returns, that would explain the silence in the logs (as well the absence of results in connection information).

How did the telnet respond?
If you can paste the results of both the `ping 4.2.2.2` and `telnet www.w3.org 80` with contents (piping this text into telnet wont work):

```
GET / HTTP/1.1
Host: www.w3.org
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)

```

Cheers,

**Comment by kvedaa** [comment]
As you can see at the end, I am playing with the use of piping in the exit to control the wait time to bail out of telnet…

KENs-iMac:bash ken$ telnet 4.2.2.2 80
Trying 4.2.2.2...
telnet: connect to address 4.2.2.2: Operation timed out
telnet: Unable to connect to remote host
KENs-iMac:bash ken$ telnet www.w3.org 80
Trying 128.30.52.100...
Connected to www.w3.org.
Escape character is '^]'.
Connection closed by foreign host.
KENs-iMac:bash ken$ ping -t3 4.2.2.2
PING 4.2.2.2 (4.2.2.2): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

--- 4.2.2.2 ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
KENs-iMac:bash ken$ ping -t3 www.w3.org
PING www.w3.org (128.30.52.100): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

--- www.w3.org ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
KENs-iMac:bash ken$ 
KENs-iMac:bash ken$ 
KENs-iMac:bash ken$ 
KENs-iMac:bash ken$ ping -t3 cnn.com
PING cnn.com (157.166.226.25): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

--- cnn.com ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
KENs-iMac:bash ken$ echo exit | telnet cnn.com 80
Trying 157.166.226.26...
Connected to cnn.com.
Escape character is '^]'.
Connection closed by foreign host.
KENs-iMac:bash ken$ 

-- 
Ken Vedaa
Sent with Airmail

On June 7, 2015 at 1:21:40 AM, Hugo Corbucci (notifications@github.com) wrote:

hmmm I had similar issues when I was running pings from virtual machines in network blocked clouds. If the ping program never returns, that would explain the silence in the logs (as well the absence of results in connection information).

How did the telnet respond?
If you can paste the results of both the ping 4.2.2.2 and telnet www.w3.org 80 with contents (piping this text into telnet wont work):

GET / HTTP/1.1
Host: www.w3.org
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)

Cheers,

**Comment by hugocorbucci** [comment]
So it seems like you might have your mac firewall enabled to block outgoing icmp (the protocol ping uses): http://osxdaily.com/2013/08/28/block-all-incoming-network-connections-mac-os-x/.
However, it is unexpected that telnet is unable to reach www.w3.org too. It seems like the network you're on has a very limited outgoing traffic for only whitelisted IP addresses. I'll work on providing an interface to specify which servers should be used to verify the connection.

Telnet is a quite unfriendly command line tool to interact with.
I will look into using actual cocoa libraries and not rely on command line tools as those are likely to use something that the firewall won't block.

For now, I will try to find out how I can credit you back from the purchase at the apple store.

Sorry for not being able to help you much further.

**Comment by kvedaa** [comment]
Don't worry about the credit, the price was small,and you have made more
than an honest effort. Plus it lead mope to your github page and the bash
script that gives me something to experiment with.
