### ISSUE TITLE
log interval

### ISSUE THREAD

**Issue by scottmaui** [hugocorbucci/network-monitor#4]
Is it possible to customize the interval that it checks status and writes it to the log file?

**Comment by hugocorbucci** [comment]
Yes. Working on a preference panel.

**Comment by hugocorbucci** [comment]
Commit d0722cb18eaa8b2f0f3e99c1bbb41b9cb2bd678d should have referenced and closed this.
The new preference pane allows to change both interval between checks and timeouts.
